name:         eqdb_web
version:      0.0.0
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  Web frontend for EqDB
homepage:     https://github.com/eqdb/web
environment:
  sdk:        '>=1.8.0 <2.0.0'

dependencies:
  sass:     ^0.4.2
  browser:  ^0.10.0+2
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- sass:
    style: compressed
- $dart2js:
    minify: true
- dart_to_js_script_rewriter
