name:         eqdb_web
version:      0.0.0
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  Web frontend for EqDB
homepage:     https://github.com/eqdb/web
environment:
  sdk:        '>=1.8.0 <2.0.0'

dependencies:
  sass: ^0.4.2

transformers:
- sass:
    style: compressed
- $dart2js:
    minify: true
